{% set version = "3.0.0" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}
package:
  name: openmpi
  version: {{ version }}

source:
  fn: openmpi-{{ version }}.tar.bz2
  url: https://www.open-mpi.org/software/ompi/v{{ minor_version }}/downloads/openmpi-{{ version }}.tar.bz2
  sha256: f699bff21db0125d8cccfe79518b77641cd83628725a1e1ed3e45633496a82d7

about:
    home: https://www.open-mpi.org/
    license: BSD 3-Clause
    license_family: BSD
    summary: 'An open source Message Passing Interface implementation.'
    description: |
        The Open MPI Project is an open source Message Passing Interface
        implementation that is developed and maintained by a consortium of academic,
        research, and industry partners.
    doc_url: https://www.open-mpi.org/doc/
    dev_url: https://github.com/open-mpi/ompi

build:
    number: 0
    features:
        - openmpi
        - psm2

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}

test:
    requires:
        - {{ compiler('c') }}
    files:
        - tests/helloworld.c
        - tests/helloworld.cxx
        - tests/helloworld.f
        - tests/helloworld.f90
    commands:
        - conda inspect objects openmpi

extra:
    recipe-maintainers:
        - willfurnass
